# Generated by Django 5.0.7 on 2024-11-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
    ]
