# Generated by Django 5.0.7 on 2024-11-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
