# Generated by Django 5.0.7 on 2024-11-10 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
